import type { Metadata } from "next";
import { Bricolage_Grotesque, Inter } from "next/font/google";
import "./globals.css";
import SmoothScroll from "@/components/scroll/SmoothScroll";
import RouteTransitionOverlay from "@/components/RouteTransitionOverlay";

const primaryFont = Bricolage_Grotesque({
  variable: "--font-bricolage",
  weight: "400"
});

const secondFont = Inter({
  variable: "--font-inter",
  weight: "400"
});

export const metadata: Metadata = {
  title: "Cehwin Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${primaryFont.variable} ${secondFont.variable} h-full antialiased bg-neutral-950`}
    >
      <body className="min-h-full flex flex-col bg-neutral-950">
        {/* <SmoothScroll> */}
        <RouteTransitionOverlay/>
          {children}
        {/* </SmoothScroll> */}
      </body>
    </html>
  );
}
